<?php

$awardDefaults = json_encode(['one' => '0', 'tow' => '0', 'theree' => '0']);
$limitList = json_encode(['free' => 100, 'all' => 100]);
$cronStatus = json_encode([
    'day' => true,
    'volume' => true,
    'remove' => false,
    'remove_volume' => false,
    'test' => false,
    'on_hold' => false,
    'uptime_node' => false,
    'uptime_panel' => false,
]);
$keyboardMain = '{"keyboard":[[{"text":"text_sell"},{"text":"text_extend"}],[{"text":"text_usertest"},{"text":"text_wheel_luck"}],[{"text":"text_Purchased_services"},{"text":"accountwallet"}],[{"text":"text_affiliates"},{"text":"text_Tariff_list"}],[{"text":"text_support"},{"text":"text_help"}]]}';

return [
    'create' => <<<SQL
        Bot_Status varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
        roll_Status varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
        get_number varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
        iran_number varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
        NotUser varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
        Channel_Report varchar(600) NULL,
        limit_usertest_all varchar(600) NULL,
        affiliatesstatus varchar(600) NULL,
        affiliatespercentage varchar(600) NULL,
        removedayc varchar(600) NULL,
        showcard varchar(200) NULL,
        numbercount varchar(600) NULL,
        statusnewuser varchar(600) NULL,
        statusagentrequest varchar(600) NULL,
        statuscategory varchar(200) NULL,
        statusterffh varchar(200) NULL,
        volumewarn varchar(200) NULL,
        inlinebtnmain varchar(200) NULL,
        verifystart varchar(200) NULL,
        id_support varchar(200) NULL,
        statusnamecustom varchar(100) NULL,
        statuscategorygenral varchar(100) NULL,
        statussupportpv varchar(100) NULL,
        agentreqprice varchar(100) NULL,
        bulkbuy varchar(100) NULL,
        on_hold_day varchar(100) NULL,
        cronvolumere varchar(100) NULL,
        verifybucodeuser varchar(100) NULL,
        scorestatus varchar(100) NULL,
        Lottery_prize TEXT NULL,
        wheelـluck varchar(45) NULL,
        wheelـluck_price varchar(45) NULL,
        btn_status_extned varchar(45) NULL,
        daywarn varchar(45) NULL,
        categoryhelp varchar(45) NULL,
        linkappstatus varchar(45) NULL,
        wheelagent varchar(45) NULL,
        Lotteryagent varchar(45) NULL,
        statusfirstwheel varchar(45) NULL,
        statuslimitchangeloc varchar(45) NULL,
        Debtsettlement varchar(45) NULL,
        Dice varchar(45) NULL,
        keyboardmain TEXT NOT NULL,
        statusnoteforf varchar(45) NOT NULL,
        statuscopycart varchar(45) NOT NULL,
        timeauto_not_verify varchar(20) NOT NULL,
        status_keyboard_config varchar(20) NULL,
        cron_status TEXT NOT NULL,
        text_edit JSON NULL,
        limitnumber varchar(200) NULL,
        webhook_secret varchar(200) NOT NULL DEFAULT ''
        SQL,
    'seedOnCreate' => [
        [
            'Bot_Status' => 'botstatuson',
            'roll_Status' => 'rolleon',
            'get_number' => 'offAuthenticationphone',
            'limit_usertest_all' => '1',
            'iran_number' => 'offAuthenticationiran',
            'NotUser' => 'offnotuser',
            'affiliatesstatus' => 'offaffiliates',
            'affiliatespercentage' => '0',
            'removedayc' => '0',
            'showcard' => '1',
            'statuscategory' => 'offcategory',
            'numbercount' => '0',
            'statusnewuser' => 'onnewuser',
            'statusagentrequest' => 'onrequestagent',
            'volumewarn' => '2',
            'inlinebtnmain' => 'offinline',
            'verifystart' => 'offverify',
            'statussupportpv' => 'offpvsupport',
            'statusnamecustom' => 'offnamecustom',
            'statuscategorygenral' => 'offcategorys',
            'agentreqprice' => '0',
            'cronvolumere' => '5',
            'bulkbuy' => 'onbulk',
            'on_hold_day' => '4',
            'verifybucodeuser' => 'offverify',
            'scorestatus' => '0',
            'Lottery_prize' => $awardDefaults,
            'wheelـluck' => '0',
            'wheelـluck_price' => '0',
            'daywarn' => '2',
            'categoryhelp' => '0',
            'linkappstatus' => '0',
            'wheelagent' => '0',
            'Lotteryagent' => '0',
            'statusfirstwheel' => '1',
            'statuslimitchangeloc' => '1',
            'limitnumber' => $limitList,
            'Debtsettlement' => '0',
            'Dice' => '0',
            'keyboardmain' => $keyboardMain,
            'statusnoteforf' => '0',
            'statuscopycart' => '0',
            'timeauto_not_verify' => '1',
            'status_keyboard_config' => '0',
            'cron_status' => $cronStatus,
        ],
    ],
    'columns' => [
        ['Bot_Status', 'botstatuson', 'VARCHAR(200)'],
        ['roll_Status', 'rolleon', 'VARCHAR(200)'],
        ['get_number', 'onAuthenticationphone', 'VARCHAR(200)'],
        ['iran_number', 'offAuthenticationiran', 'VARCHAR(200)'],
        ['NotUser', 'offnotuser', 'VARCHAR(200)'],
        ['Channel_Report', '0', 'VARCHAR(200)'],
        ['limit_usertest_all', '1', 'VARCHAR(200)'],
        ['affiliatesstatus', 'offaffiliates', 'VARCHAR(600)'],
        ['affiliatespercentage', '0', 'VARCHAR(600)'],
        ['removedayc', '1', 'VARCHAR(200)'],
        ['showcard', '1', 'VARCHAR(200)'],
        ['numbercount', '0', 'VARCHAR(600)'],
        ['statusnewuser', 'onnewuser', 'VARCHAR(600)'],
        ['statusagentrequest', 'onrequestagent', 'VARCHAR(600)'],
        ['statuscategory', 'offcategory', 'VARCHAR(600)'],
        ['volumewarn', '2', 'VARCHAR(200)'],
        ['inlinebtnmain', 'offinline', 'VARCHAR(200)'],
        ['verifystart', 'offverify', 'VARCHAR(200)'],
        ['id_support', '0', 'VARCHAR(100)'],
        ['statusnamecustom', 'offnamecustom', 'VARCHAR(100)'],
        ['statuscategorygenral', 'offcategorys', 'VARCHAR(100)'],
        ['statussupportpv', 'offpvsupport', 'VARCHAR(100)'],
        ['agentreqprice', '0', 'VARCHAR(100)'],
        ['bulkbuy', 'onbulk', 'VARCHAR(100)'],
        ['on_hold_day', '4', 'VARCHAR(100)'],
        ['cronvolumere', '5', 'VARCHAR(100)'],
        ['verifybucodeuser', 'offverify', 'VARCHAR(100)'],
        ['scorestatus', '0', 'VARCHAR(100)'],
        ['Lottery_prize', $awardDefaults, 'TEXT'],
        ['wheelـluck', '0', 'varchar(45)'],
        ['wheelـluck_price', '0', 'varchar(45)'],
        ['btn_status_extned', '0', 'varchar(45)'],
        ['daywarn', '2', 'varchar(45)'],
        ['categoryhelp', '0', 'varchar(45)'],
        ['linkappstatus', '0', 'varchar(45)'],
        ['wheelagent', '1', 'varchar(45)'],
        ['Lotteryagent', '1', 'varchar(45)'],
        ['statusfirstwheel', '0', 'varchar(45)'],
        ['statuslimitchangeloc', '0', 'varchar(45)'],
        ['limitnumber', $limitList, 'varchar(200)'],
        ['Debtsettlement', '1', 'varchar(45)'],
        ['Dice', '0', 'varchar(45)'],
        ['keyboardmain', $keyboardMain, 'TEXT'],
        ['statusnoteforf', '1', 'varchar(20)'],
        ['statuscopycart', '0', 'varchar(20)'],
        ['timeauto_not_verify', '4', 'varchar(20)'],
        ['status_keyboard_config', '1', 'varchar(20)'],
        ['cron_status', $cronStatus, 'TEXT'],
        ['text_edit', '{}', 'JSON'],
        ['webhook_secret', null, "VARCHAR(200) NOT NULL DEFAULT ''"],
    ],
];
